package main

func (g *Game) SetupBoardSpaces() {
	g.Board.Spaces = [40]Space{
		&NeutralSpace{Name: "Go"},
		&Property{Name: "Mediterranean Avenue", Price: 60, Rent: 2, Group: "purple"},
		&CardDrawSpace{Name: "Community Chest", CardDeck: *g.Chest},
		&Property{Name: "Baltic Avenue", Price: 60, Rent: 4, Group: "purple"},
		&TaxSpace{Name: "Income Tax", Amount: 200},
		&Property{Name: "Reading Railroad", Price: 200, Rent: 25, Group: "railroad"},
		&Property{Name: "Oriental Avenue", Price: 100, Rent: 6, Group: "light-blue"},
		&CardDrawSpace{Name: "Chance", CardDeck: *g.Chance},
		&Property{Name: "Vermont Avenue", Price: 100, Rent: 6, Group: "light-blue"},
		&Property{Name: "Connecticut Avenue", Price: 120, Rent: 8, Group: "light-blue"},
		&GoToJailSpace{Name: "Visting Jail"},
		&Property{Name: "St. Charles Place", Price: 140, Rent: 10, Group: "pink"},
		&Property{Name: "Electric Company", Price: 150, Rent: 0, Group: "utility"},
		&Property{Name: "States Avenue", Price: 140, Rent: 10, Group: "pink"},
		&Property{Name: "Virginia Avenue", Price: 160, Rent: 12, Group: "pink"},
		&Property{Name: "Pennsylvania Railroad", Price: 200, Rent: 25, Group: "railroad"},
		&Property{Name: "St. James Place", Price: 180, Rent: 14, Group: "orange"},
		&CardDrawSpace{Name: "Community Chest", CardDeck: *g.Chest},
		&Property{Name: "Tennessee Avenue", Price: 180, Rent: 14, Group: "orange"},
		&Property{Name: "New York Avenue", Price: 200, Rent: 16, Group: "orange"},
		&NeutralSpace{Name: "Free Parking"},
		&Property{Name: "Kentucky Avenue", Price: 220, Rent: 18, Group: "red"},
		&CardDrawSpace{Name: "Chance", CardDeck: *g.Chance},
		&Property{Name: "Indiana Avenue", Price: 220, Rent: 18, Group: "red"},
		&Property{Name: "Illinois Avenue", Price: 240, Rent: 20, Group: "red"},
		&Property{Name: "B. & O. Railroad", Price: 200, Rent: 25, Group: "railroad"},
		&Property{Name: "Atlantic Avenue", Price: 260, Rent: 22, Group: "yellow"},
		&Property{Name: "Ventnor Avenue", Price: 260, Rent: 22, Group: "yellow"},
		&Property{Name: "Water Works", Price: 150, Rent: 0, Group: "utility"},
		&Property{Name: "Marvin Gardens", Price: 280, Rent: 24, Group: "yellow"},
		&GoToJailSpace{Name: "Go To Jail"},
		&Property{Name: "Pacific Avenue", Price: 300, Rent: 26, Group: "green"},
		&Property{Name: "North Carolina Avenue", Price: 300, Rent: 26, Group: "green"},
		&CardDrawSpace{Name: "Community Chest", CardDeck: *g.Chest},
		&Property{Name: "Pennsylvania Avenue", Price: 320, Rent: 28, Group: "green"},
		&Property{Name: "Short Line", Price: 200, Rent: 25, Group: "railroad"},
		&CardDrawSpace{Name: "Chance", CardDeck: *g.Chance},
		&Property{Name: "Park Place", Price: 350, Rent: 35, Group: "blue"},
		&TaxSpace{Name: "Luxury Tax", Amount: 100},
		&Property{Name: "Boardwalk", Price: 400, Rent: 50, Group: "blue"},
	}
}
